---
title: Safest Route to Binghamton University
excerpt: Safest Bike Route from Binghamton (city) to Binghamton (university)
tags: cycling, binghamton, biking
season: summer 2012
type: blog
layout: post
---

Hello! You somehow found this page so I'll assume you were looking for a convenient and safe route to Binghamton University from anywhere in Binghamton "proper". 

*Some background.* This is the safest route I have found to get to Binghamton University assuming you're coming from the general vicinity of central Binghamton. After several years' experience biking in much larger cities, I was surprised to find that biking in Binghamton made me uncomfortable at times, and this route helped to alleviate much of that stress (at least for my daily commute). There are a few modest climbs, but after a few trips you'll hardly even notice them! If you *really* want to get your blood pumping there are a few places you can take a left off of Moore to add a bit more climbing to the trip.

Note that this route is only efficient if you are east of, say, Beethoven Street on Binghamton's west side. Even if you aren't you might prefer this route---especially in the winter when the bike lanes and sidewalks of the 201 bridge are not cleared of ice and debris (yea, like all winter). Happy Trails!

*Update.* A fully-featured dedicated bike path [is in the works](http://www.pressconnects.com/story/news/local/2016/04/29/trail-blazing-16m-pedestrian-route-would-link-bu-downtown/82344124/) to link Binghamton University to downtown, so thank your government officials for addressing this problem. 

<iframe src="https://www.google.com/maps/d/u/0/embed?mid=1OkUodDDf2kCKFbrXyYXtxfb0aqUo_Cdr" width="640" height="480"></iframe>



Step-by-step directions:

<table style="width:100%">
  <tr>
    <th>Direction</th>
    <th>Distance</th> 
  </tr>
  <tr>
    <td>Take the pedestrian bridge across the Susquehanna River</td>
    <td></td> 
  </tr>
  
    <tr>
    <td>Turn right onto Pennsylvania Ave</td>
    <td>92 ft</td> 
  </tr>
  
    <tr>
    <td>Slight left to stay on Pennsylvania Ave</td>
    <td>0.694 mi</td> 
  </tr>
  
    <tr>
    <td>Turn right onto Moore Ave</td>
    <td>0.873 mi</td> 
  </tr>
  
    <tr>
    <td>Turn right onto Hazard Hill Rd</td>
    <td>262 ft</td> 
  </tr>
  
    <tr>
    <td>Continue onto Hawthorne Rd</td>
    <td>1,168 ft</td> 
  </tr>
  
    <tr>
    <td>Turn left onto Clifton Blvd</td>
    <td>0.925 mi</td> 
  </tr>
  
    <tr>
    <td>Turn left onto Clubhouse Rd</td>
    <td>0.413 mi</td> 
  </tr>
  
    <tr>
    <td>Turn left onto Country Club Rd</td>
    <td>0.314 mi</td> 
  </tr>
  
    <tr>
    <td>Turn right onto Washington Dr</td>
    <td>0.290 mi</td> 
  </tr>
  
    <tr>
    <td>Turn right onto Lehigh Ave</td>
    <td>341 ft</td> 
  </tr>
  
    <tr>
    <td>Continue onto E Access Rd til you're there!</td>
    <td></td> 
  </tr>

</table>




